### ISSUE TITLE
Job doesn't send to Afanasy in Blender 2.8

### ISSUE THREAD

**Issue by ialebedev** [CGRU/cgru#464]
Hi

I have a few render layers.
And when I try to send the job with one of the render layers to afanasy , I jet this error.

`Traceback (most recent call last):
  File "/opt/cgru/plugins/blender/addons/cgru_tools/operators.py", line 114, in execute
    layers = utils.layers_get(active_scene)
  File "/opt/cgru/plugins/blender/addons/cgru_tools/utils.py", line 39, in layers_get
    obj_colls = object.users_collection # get all collections object is in
AttributeError: 'NoneType' object has no attribute 'users_collection'

location: <unknown location>:-1
`
Any ideas?

**Comment by timurhai** [comment]
Hi!
At first you should say, where you got addon for a Blender 2.8, as native addon in the latest release does not.

**Comment by ialebedev** [comment]
Sure, from the lates release

The system is Debian 10 x86_64

**Comment by timurhai** [comment]
It should not work.
You can try this:
http://rules.cgru.info/#/downloads/blender
Here was a small discusson:
http://forum.cgru.info/viewtopic.php?f=7&t=3209&start=10

**Comment by ialebedev** [comment]
Sorry

I've forgotten. I already used that version of the plugin.
But any way I've replaced the old one on my server with the new from your link, to be sure.

The error still the same.

What is interesting is that few hours ago some other layers were send on the server without any problems.

**Comment by ialebedev** [comment]
It seems to me, that the problem appears when I try to render subcollections (collections which are inside other collections). Because there is no problems when I render collections which are on top of the hierarchy in outliner.

**Comment by ialebedev** [comment]
Timur, hi

Any ideas?

**Comment by timurhai** [comment]
Hi!
I have not launched Blender 2.8, yet.
